#!/bin/bash

# bu - backup. This script backs up a file into the directory `.bu`. A nice tool
# for when things aren't/shouldn't be in Git

BUD=".bu"

function colorize() {
  COL='\033[0;3'$1'm'
  RST='\033[0m'
  printf "${COL}$2${RST}\n"
}

function error()   { colorize 1 "$1"; }
function success() { colorize 2 "$1"; }
function warn()    { colorize 3 "$1"; }
function info()    { colorize 6 "$1"; }

function check_dir(){
  if [ ! -d .bu ]; then
    info "Making directory .bu"
    mkdir $BUD
  fi
}

function list(){
  if [ ! -d $BUD ]; then
    error "No .bu directory"
    exit 0
  fi

  counter=0
  if [ ! -z $1 ]; then
    info "Checking backups with filter: $1"
    items=$(ls $BUD|grep "$1")
  else
    items=$(ls -1 $BUD)
  fi

  for i in $items
  do
    echo $i
    ((count++))
  done

  info "$count files"
}

function backup(){
  check_dir
  prefix=$(date +%FT%T)
  target="$BUD/${prefix}_${1}"
  cp $1 $target
  info "Backed up $1 to $target"
}

function restore_name(){
  name=$(echo $1| sed 's/^[^_]*//;s/^_//')
  echo $name
}

function restore(){
  if [ ! -e $BUD/$1 ]; then
    error "$BUD/$1 does not exist to restore"
  fi
  rn=$(restore_name $1)

  cp $BUD/$1 ../$rn
  info "restored $BUD/$1 to $rn"
  mv $BUD/$1 $BUD/$1-restored
  info "renamed $BUD/$1 to $BUD/$1-restored to denote restored"
}

function compare(){
  if [ ! -e $BUD/$1 ]; then
    error "$BUD/$1 does not exist to restore"
  fi
  current=$(restore_name $1)

  info "comparing $BUD/$1 to $current"
  diff -urN $BUD/$1 $current
}

function help(){
  error "Enter a file to backup"
  info "Other actions available: ls, ls <filter>, restore"

}

if [ -z $1 ]; then
  help
  exit 1
fi


if [ $1 == "ls" ]; then
  if [ ! -z $2 ]; then
    list $2
  else
    list
  fi
  exit 0
fi

if [ $1 == "restore" ]; then
  if [ ! -z $2 ]; then
    restore $2
  else
    error "'restore' requires a file name"
    exit 1
  fi
  exit 0
fi

if [ $1 == "compare" ]; then
  if [ ! -z $2 ]; then
    compare $2
  else
    error "'compare' requires a file name"
    exit 1
  fi
  exit 0
fi

backup $1

