#!/bin/bash

if [ ! -e ~/.gitconfig.local ]; then
  cat >> ~/.gitconfig.local << 'EOT'
[user]
  name = "Scott Walsh"
  email = scott@invisiblethreat.ca
EOT

  echo "~/.gitconfig.local created. Defaulted email to scott@invisiblethreat.ca"
fi

touch ~/.local_profile.zsh
touch ~/.local_aliases.zsh
touch ~/.local_exports.zsh

# just uncomment this for auto-tmuxing
echo "#export TMUX_AUTO=1" >> ~/.local_exports.zsh
echo "Edit ~/.local_exports.zsh to auto-tmux this host"

echo "Local files for zsh created"
