#!/bin/bash

function get-version(){
  found=$(which nvim > /dev/null; echo $?)
  if [ "$found" == "0" ]; then
    nvim --version|grep "NVIM v" |awk '{print $2}'
  else
    echo "not installed"
  fi
}

function update-linux(){
  cd ~/bin
  curl -LOs https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  chmod u+x nvim.appimage
  ln -nsf nvim.appimage nvim
}

function update-darwin(){
  brew unlink neovim
  brew update && brew install neovim --HEAD
}

old=$(get-version)
echo -n "Starting update... "

os=$(uname)

if [ "$os" == "Linux" ]; then
  echo -n "Updating neovim for $os... "
  update-linux
elif [[ "$os" == "Darwin" ]]; then
  echo -n "Updating neovim for $os... "
  update-darwin
else
  printf "\n Unsupported OS"
  exit 1
fi

echo "Done."
new=$(get-version)

if [ "$old" != "$new" ]; then
  echo "nvim updated from $old to $new"
  echo "You may need to rebuild Treesitter with :TSUpdate"
else
  echo "nvim version remains at $old"
fi

