#!/bin/bash

# Install OMZ
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# Create the custom theme path
mkdir -p ~/.oh-my-zsh/custom/themes

# Link the theme in the repo into the OMZ path
ln -s ~/.zsh/automaton.zsh-theme ~/.oh-my-zsh/custom/themes/automaton.zsh-theme

# Install plugins
cd ~.oh-my-zsh/custom/plugins/
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
