#!/bin/bash

# make the directory if it doesn't exist
CONFIG="$HOME/.config"

if [ ! -e $CONFIG ]; then
  mkdir -p $CONFIG

fi

# link the rc and vim-plug code. Having the vim-plug code in the repo solves
# bootstrapping.
ln -nsf $PWD/nvim/ $CONFIG/nvim

# Install plugins and exit
nvim +PlugInstall -c x -c x
