#!/bin/bash

PACKAGES="aptitude apt-file apt-transport-https bind9-host colordiff curl jq tree tmux neovim htop zsh git strace zsh-syntax-highlighting"

apt-get update
apt-get install -y $PACKAGES

if [ "$(uname -m)" != "x86_64" ]; then
  echo "Wrong arch for Neovim appimage"
  exit
fi

# get the nightly nvim and put it in the ~/bin
cd ~/bin
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
ln -nsf nvim.appimage nvim
echo "alias vim=nvim" >> ~/.local_aliases.zsh
