#!/bin/bash
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall

#do the fontconfig stuff here.
if [ -e ~/.fonts ]; then
  mkdir ~/.fonts
fi

cd ~/.fonts
wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf

fc-cache -vf ~/.fonts
