#!/bin/bash


./config_brew
./config_vscode
# Add the path for gnubin, so things like ls --color=auto don't break for interactive logins
echo "PATH=/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:\$PATH" >> $HOME/.local_exports.zsh
# Death to .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

