#!/bin/bash

PACKAGES="aptitude apt-file apt-transport-https bind9-host colordiff curl jq tree tmux htop zsh git strace zsh-syntax-highlighting python3-pip python3-venv"

apt-get update
apt-get install -y $PACKAGES

if [ "$(uname -m)" != "x86_64" ]; then
  echo "Wrong arch for Neovim appimage. Building from source"
  apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip doxygen
  cd ~/git
  git clone https://github.com/neovim/neovim.git
  cd neovim
  make && make install
  exit
fi

$HOME/bin/update-nvim
