#!/bin/bash

if [ ! -e /usr/local/bin/brew ]; then
 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install \
        awscli \
        bat \
        bgrep \
        colordiff \
        coreutils \
        docker-compose \
        docker-machine \
        exa \
        gcc \
        gnu-sed \
        go \
        hub \
        jq \
        jsonlint \
        lua \
        lz4 \
        mutt \
        perl \
        r \
        readline \
        ripgrep \
        ruby \
        tig \
        tmux \
        vim \
        wget

brew cask install \
        1password \
        1password-cli \
        clipy \
        google-chrome \
        slack
