#!/bin/bash

# Installs take place via config_debian and config_brew depending on the OS.
# Debian systems use the "universal" appimage since packages are often stale

# make the directory if it doesn't exist
CONFIG="$HOME/.config"

if [ ! -e $CONFIG ]; then
  mkdir -p $CONFIG

fi

# link the rc and vim-plug code. Having the vim-plug code in the repo solves
# bootstrapping.
ln -nsf $PWD/nvim/ $CONFIG/nvim

# For some of the providers
pip3 install neovim

# Install plugins and exit
nvim +PlugInstall -c x -c x
