#!/bin/bash
#
# By my convention, the files linked out of this directory named the same as
# their corresponding "dotfile", but not prefixed with a "."
#
PWD=$(pwd)
FILES="bash_aliases bash_exports bash_profile bash_prompt gitconfig tmux tmux.conf vim vimrc zsh zshrc"

# You're in a bad place if this happens
if [ -z $HOME ]
then
    printf "\$HOME is not set\n"
fi

for i in $FILES
do
  printf "Linking $PWD/$i to $HOME/.$i..."
  if [ -e $HOME/.$i ]
  then
    mv $HOME/.$i $HOME/.$i-old
  fi
  ln -nsf $PWD/$i $HOME/.$i
  printf " Done.\n"
done

./config_vim
./config_zsh
