#!/bin/bash

cat << EOT >> ~/.bash_profile

if [ -e ~/.bash_prompt ]; then
  source ~/.bash_prompt
fi

if [ -e ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -e ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi
EOT

echo "Now run: source ~/.bash_profile"
