#!/bin/bash

cat << EOT > ~/.gitconfig.local
#[user]
#  name = "Your Name"
#  email = name@example.com
EOT

echo "~/.gitconfig.local created. Edit it before commiting."

touch ~/.local_profile.zsh
touch ~/.local_aliases.zsh
touch ~/.local_exports.zsh

# just uncomment this for auto-tmuxing
echo "#export TMUX_AUTO=1" >> ~/.local_exports.zsh
echo "Edit ~/.local_exports.zsh to auto-tmux this host"

echo "Local files for zsh created"
