#!/bin/bash

AUTO="$HOME/.vim/pack/autoload/start"

# Autoload plugins
if [ -d $AUTO ]; then
  echo "Vim plugin directory of $AUTO found. Skipping plugin configuration."
  exit 1
fi

mkdir -p $AUTO
for i in $(cat vim/plugin-repos)
do
  REPO=$(basename -s .git $i)
  echo "Cloning plugin $i"
  git clone --depth 1 --quiet $i $AUTO/$REPO >/dev/null
done

# Link colors
COLORS="$HOME/.vim/colors"
if [ ! -d $HOME/.vim/colors ];then
  mkdir -p $COLORS
fi

for i in $(find $AUTO -type d -name colors )
do
  for j in $(find $i -type f -name "*.vim")
  do
    echo "Linking $j"
    ln -nsf $j $COLORS/
  done
done
